version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing AWS SAM CLI..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template infrastructure/template.yaml
      
  build:
    commands:
      - echo "Building all Lambda functions..."
      - sam build --template infrastructure/template.yaml
      
      # Build frontend
      - echo "Building frontend..."
      - cd frontend
      - npm install
      - npm run build
      - cd ..
      
  post_build:
    commands:
      - echo "Packaging application..."
      - |
        sam package \
          --template-file .aws-sam/build/template.yaml \
          --s3-bucket $BUILD_BUCKET \
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - infrastructure/**/*
    - frontend/dist/**/*
